name: ${parent.name}
version: ${project.version}
main: ${project.groupId}.${project.artifactId}.${parent.name}Plugin
softdepend: [LuckPerms, Vault]
author: Chickenpowerrr
description: ${project.description}

commands:
  ranksync:
    description: Link your account to another service
    aliases: [link, sync, synchronize, syncrank, synchronizerank, giverank]
    permission: ranksync.command.ranksync
  unsync:
    description: Unlink your account from another service
    aliases: [unlink, unranksync, unsynchronize, unsyncrank, unsynchronizerank, revertrank]
    permission: ranksync.command.unsync